apiVersion: v1
kind: Service
metadata:
  name: {{ include "cadvisor.fullname" . }}
  labels:
    {{- include "cadvisor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    {{- include "cadvisor.selectorLabels" . | nindent 4 }}
